[package]
name = "sunscreen-iai-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sunscreen = "0.8.1"

[dev-dependencies]
iai = "0.1"

[[bench]]
name = "benchmark_iai"
harness = false